# Generated by Django 3.0.7 on 2021-04-06 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GRH', '0001_initial'),
        ('Inscriptions', '0001_initial'),
        ('Ecole', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationFraisEleve',
            fields=[
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé_le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié_le')),
                ('paiement_frais_numero', models.AutoField(primary_key=True, serialize=False, verbose_name='Paiement frais n°:')),
                ('frais', models.CharField(choices=[('Frais Mensuel', 'Frais Mensuel'), ('Frais Trimesrtiel', 'Frais trimestriel'), ('Frais Annuel', 'Frais Annuel'), ('Assurance', 'Assurance'), ("Dossier d'examen", "Dossier d'examen"), ('Macaron', 'Macaron'), ("Tenu d'eps", "Tenu d'eps")], max_length=100, verbose_name='Intitulé du frais')),
                ('montant', models.FloatField()),
            ],
            options={
                'db_table': 'Configuration_Frais_Eleve',
            },
        ),
        migrations.CreateModel(
            name='ConfigurationSalaireEnseignant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé_le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié_le')),
                ('categorie_enseignant', models.CharField(choices=[('Primaire', 'Enseigne au Primaire'), ('College', 'Enseigne au College')], max_length=30, verbose_name="Catégorie d'employé :")),
                ('salaire_defini', models.FloatField(verbose_name='Salaire défini')),
            ],
            options={
                'db_table': 'Configuration_Salaire_Enseignant',
            },
        ),
        migrations.CreateModel(
            name='PaiementSalairePersonnel',
            fields=[
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé_le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié_le')),
                ('paiement_numero', models.AutoField(primary_key=True, serialize=False, verbose_name='Paiement numéro =>')),
                ('mois_paiement', models.CharField(choices=[('Octobre', 'Octobre'), ('Novembre', 'Novembre'), ('Décembre', 'Décembre'), ('Janvier', 'Janvier'), ('Février', 'Février'), ('Mars', 'Mars'), ('Avril', 'Avril'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Autres', (('Juillet', 'Juillet'), ('Aout', 'Aout'), ('Septembre', 'Septembre')))], max_length=50)),
                ('montant_a_payer', models.FloatField()),
                ('montant_deja_paye', models.FloatField(default=0, editable=False)),
                ('montant_restant', models.FloatField(editable=False)),
                ('statut', models.BooleanField(blank=True, editable=False, help_text="Est coché lorsque l'élève a réglé totalement")),
                ('nom_personnel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='personnel_a_payer', to='GRH.Personnel')),
            ],
            options={
                'db_table': 'Paiement_Salaire_Personnel',
            },
        ),
        migrations.CreateModel(
            name='PaiementSalaireEnseignant',
            fields=[
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé_le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié_le')),
                ('paiement_numero', models.AutoField(primary_key=True, serialize=False, verbose_name='Paiement numéro =>')),
                ('mois_paiement', models.CharField(choices=[('Octobre', 'Octobre'), ('Novembre', 'Novembre'), ('Décembre', 'Décembre'), ('Janvier', 'Janvier'), ('Février', 'Février'), ('Mars', 'Mars'), ('Avril', 'Avril'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Autres', (('Juillet', 'Juillet'), ('Aout', 'Aout'), ('Septembre', 'Septembre')))], max_length=50)),
                ('heures_effectuees', models.CharField(default='8h de cours enseignees', editable=False, max_length=50)),
                ('montant_a_payer', models.FloatField()),
                ('montant_deja_paye', models.FloatField(default=0, editable=False)),
                ('montant_restant', models.FloatField(editable=False)),
                ('statut', models.BooleanField(blank=True, editable=False, help_text="Est coché lorsque l'élève a réglé totalement")),
                ('nom_enseignant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='enseignant_a_payer', to='Ecole.Enseignant')),
            ],
            options={
                'db_table': 'Paiement_Salaire_Enseignant',
            },
        ),
        migrations.CreateModel(
            name='PaiementFrais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé_le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié_le')),
                ('mois', models.CharField(blank=True, choices=[('Octobre', 'Octobre'), ('Novembre', 'Novembre'), ('Décembre', 'Décembre'), ('Janvier', 'Janvier'), ('Février', 'Février'), ('Mars', 'Mars'), ('Avril', 'Avril'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Autres', (('Juillet', 'Juillet'), ('Aout', 'Aout'), ('Septembre', 'Septembre')))], max_length=30, null=True, verbose_name='Mois à payer')),
                ('montant_a_payer', models.FloatField()),
                ('montant_deja_paye', models.FloatField(default=0, editable=False)),
                ('montant_restant', models.FloatField(editable=False)),
                ('statut', models.BooleanField(blank=True, editable=False, help_text="Est coché lorsque l'élève a réglé totalement")),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='eleve_payant', to='Inscriptions.Eleve')),
                ('montant_frais', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to='Finances.ConfigurationFraisEleve')),
                ('type_frais', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='type_frais', to='Finances.ConfigurationFraisEleve', verbose_name='Type de frais A payer')),
            ],
            options={
                'verbose_name_plural': 'frais',
                'db_table': 'Paiement_frais',
            },
        ),
    ]
