# Generated by Django 3.0.7 on 2021-08-27 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GRH', '0001_initial'),
        ('Ecole', '0001_initial'),
        ('Inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationFraisEleve',
            fields=[
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé_le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié_le')),
                ('frais', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Intitulé du frais')),
                ('periodePaiement', models.CharField(max_length=100, verbose_name='Période de paiement')),
                ('montant', models.FloatField()),
                ('AnneeScolaire', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='config_frais_annee', to='Ecole.AnneeScolaire')),
            ],
            options={
                'db_table': 'Configuration_Frais_Eleve',
            },
        ),
        migrations.CreateModel(
            name='PaiementSalairePersonnel',
            fields=[
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé_le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié_le')),
                ('paiementNumero', models.AutoField(primary_key=True, serialize=False, verbose_name='Paiement numéro =>')),
                ('moisPaiement', models.CharField(choices=[('Octobre', 'Octobre'), ('Novembre', 'Novembre'), ('Décembre', 'Décembre'), ('Janvier', 'Janvier'), ('Février', 'Février'), ('Mars', 'Mars'), ('Avril', 'Avril'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Autres', (('Juillet', 'Juillet'), ('Aout', 'Aout'), ('Septembre', 'Septembre')))], max_length=50, verbose_name='Mois à payer')),
                ('montantApayer', models.FloatField(verbose_name='Montant à payer')),
                ('montantDejaPaye', models.FloatField(default=0, editable=False, verbose_name='Montant déjà payé')),
                ('montantRestant', models.FloatField(editable=False, verbose_name='Montant Restant à payer')),
                ('statut', models.BooleanField(blank=True, editable=False, help_text="Est coché lorsque l'élève a réglé totalement")),
                ('AnneeScolaire', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='salaire_personnel_annee', to='Ecole.AnneeScolaire')),
                ('nomPersonnel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='personnel_a_payer', to='GRH.Personnel', verbose_name='Nom du personnel')),
            ],
            options={
                'db_table': 'Paiement_Salaire_Personnel',
            },
        ),
        migrations.CreateModel(
            name='PaiementSalaireEnseignant',
            fields=[
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé_le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié_le')),
                ('paiementNumero', models.AutoField(primary_key=True, serialize=False, verbose_name='Paiement numéro =>')),
                ('moisPaiement', models.CharField(choices=[('Octobre', 'Octobre'), ('Novembre', 'Novembre'), ('Décembre', 'Décembre'), ('Janvier', 'Janvier'), ('Février', 'Février'), ('Mars', 'Mars'), ('Avril', 'Avril'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Autres', (('Juillet', 'Juillet'), ('Aout', 'Aout'), ('Septembre', 'Septembre')))], max_length=50, verbose_name='Mois à payer')),
                ('heuresEffectue', models.CharField(default='8h de cours enseignees', editable=False, max_length=50, verbose_name='Heures effectuées')),
                ('montantApayer', models.FloatField()),
                ('montantDejaPaye', models.FloatField(default=0, editable=False, verbose_name='Montant Déjà payé')),
                ('montantRestant', models.FloatField(editable=False, verbose_name='Montant Restant à payer')),
                ('statut', models.BooleanField(blank=True, editable=False, help_text="Est coché lorsque l'élève a réglé totalement")),
                ('AnneeScolaire', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='salaire_teacher_annee', to='Ecole.AnneeScolaire')),
                ('nomEnseignant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='enseignant_a_payer', to='Ecole.Enseignant', verbose_name="Nom de l'enseignant")),
            ],
            options={
                'db_table': 'Paiement_Salaire_Enseignant',
            },
        ),
        migrations.CreateModel(
            name='PaiementInscriptionReinscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé_le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié_le')),
                ('typeFrais', models.CharField(choices=[('Frais Inscription', 'Frais Inscription'), ('Frais Reinscription', 'Frais Reinscription')], max_length=50, null=True, verbose_name='Type de frais à payer')),
                ('montantFrais', models.FloatField(verbose_name='Montant Frais à payer')),
                ('AnneeScolaire', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='annee_scolaire_insc_reinsc', to='Ecole.AnneeScolaire')),
                ('classe', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='classe_eleve_insc_reinsc', to='Ecole.Classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='eleve_payant_insc_reinsc', to='Inscriptions.Eleve')),
            ],
            options={
                'db_table': 'Paiement_Inscription_Reinscription',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='PaiementFraisMensuels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé_le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié_le')),
                ('montantFrais', models.CharField(max_length=50, verbose_name='Montant Frais à payer')),
                ('mois', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mois à payer')),
                ('moisAsolver', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mois à solver')),
                ('montantApayer', models.FloatField(verbose_name='Montant à payer')),
                ('montantDejaPaye', models.FloatField(default=0, verbose_name='Montant déjà payé')),
                ('montantRestant', models.FloatField(verbose_name='Montant restant')),
                ('statut', models.CharField(blank=True, max_length=250)),
                ('AnneeScolaire', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='frais_mensuel_annee', to='Ecole.AnneeScolaire')),
                ('classe', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='classeEleve_payant_FM', to='Ecole.Classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='eleve_payant_FM', to='Inscriptions.Eleve')),
            ],
            options={
                'db_table': 'Paiement_frais_Mensuels',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='PaiementAutresFrais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé_le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié_le')),
                ('montantFrais', models.CharField(max_length=50, verbose_name='Montant Frais à payer')),
                ('montantApayer', models.FloatField(verbose_name='Montant à payer')),
                ('montantRestant', models.FloatField(verbose_name='Montant restant')),
                ('AnneeScolaire', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='autre_frais_annee', to='Ecole.AnneeScolaire')),
                ('classe', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='classeEleve_payant_autreFrais', to='Ecole.Classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='eleve_payant_autreFrais', to='Inscriptions.Eleve')),
                ('typeFrais', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='type_frais', to='Finances.ConfigurationFraisEleve', verbose_name='Type de frais à payer')),
            ],
            options={
                'verbose_name_plural': 'frais',
                'db_table': 'Paiement_Autres_frais',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationSalaireEnseignant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé_le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié_le')),
                ('categorieEnseignant', models.CharField(choices=[('Primaire', 'Enseigne au Primaire'), ('College', 'Enseigne au College')], max_length=30, verbose_name="Catégorie d'employé :")),
                ('salaireDefini', models.FloatField(verbose_name='Salaire défini')),
                ('AnneeScolaire', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='config_salaireTeacher_annee', to='Ecole.AnneeScolaire')),
            ],
            options={
                'db_table': 'Configuration_Salaire_Enseignant',
            },
        ),
        migrations.CreateModel(
            name='ConfigFraisInscriptionReinscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé_le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié_le')),
                ('fraisInscription', models.IntegerField()),
                ('fraisReinscription', models.IntegerField()),
                ('AnneeScolaire', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='config_inscReinsc_annee', to='Ecole.AnneeScolaire')),
                ('classe', models.OneToOneField(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='inscr_reinsc_classe', to='Ecole.Classe')),
            ],
            options={
                'db_table': 'Config_Frais_Insc_Reinsc',
            },
        ),
    ]
