# Generated by Django 3.0.7 on 2021-07-31 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole', '0001_initial'),
        ('Finances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigFraisInscriptionReinscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé_le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié_le')),
                ('fraisInscription', models.IntegerField()),
                ('fraisReinscription', models.IntegerField()),
                ('classe', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='inscr_reinsc_classe', to='Ecole.Classe')),
            ],
            options={
                'db_table': 'Config_Frais_Insc_Reinsc',
            },
        ),
    ]
