# Generated by Django 3.0.7 on 2021-10-21 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inscriptions', '0002_auto_20211021_1137'),
        ('Ecole', '0002_auto_20211021_1137'),
        ('Finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configfraisinscriptionreinscription',
            name='periodePaiement',
            field=models.CharField(default='', max_length=100, verbose_name='Période de paiement'),
        ),
        migrations.AlterField(
            model_name='configfraisinscriptionreinscription',
            name='AnneeScolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='config_inscReinsc_annee', to='Ecole.AnneeScolaire'),
        ),
        migrations.AlterField(
            model_name='configurationfraiseleve',
            name='AnneeScolaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='config_frais_annee', to='Ecole.AnneeScolaire'),
        ),
        migrations.AlterField(
            model_name='configurationfraiseleve',
            name='montant',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='configurationfraiseleve',
            name='periodePaiement',
            field=models.CharField(max_length=100, null=True, verbose_name='Période de paiement'),
        ),
        migrations.AlterField(
            model_name='configurationsalaireenseignant',
            name='AnneeScolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='config_salaireTeacher_annee', to='Ecole.AnneeScolaire'),
        ),
        migrations.AlterField(
            model_name='paiementautresfrais',
            name='AnneeScolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='autre_frais_annee', to='Ecole.AnneeScolaire'),
        ),
        migrations.AlterField(
            model_name='paiementfraismensuels',
            name='AnneeScolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='frais_mensuel_annee', to='Ecole.AnneeScolaire'),
        ),
        migrations.AlterField(
            model_name='paiementinscriptionreinscription',
            name='AnneeScolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='annee_scolaire_insc_reinsc', to='Ecole.AnneeScolaire'),
        ),
        migrations.AlterField(
            model_name='paiementinscriptionreinscription',
            name='typeFrais',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='InscReinsc_type_frais', to='Finances.ConfigurationFraisEleve', verbose_name='Type de frais à payer'),
        ),
        migrations.AlterField(
            model_name='paiementsalaireenseignant',
            name='AnneeScolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='salaire_teacher_annee', to='Ecole.AnneeScolaire'),
        ),
        migrations.AlterField(
            model_name='paiementsalairepersonnel',
            name='AnneeScolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='salaire_personnel_annee', to='Ecole.AnneeScolaire'),
        ),
        migrations.CreateModel(
            name='PaiementEveryFrais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé_le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié_le')),
                ('montantFrais', models.CharField(max_length=50, verbose_name='Montant Frais à payer')),
                ('mois', models.CharField(blank=True, max_length=30, null=True, verbose_name='Mois à payer')),
                ('moisAsolver', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Mois à solver')),
                ('montantApayer', models.FloatField(verbose_name='Montant à payer')),
                ('montantDejaPaye', models.FloatField(default=0, verbose_name='Montant déjà payé')),
                ('montantRestant', models.FloatField(verbose_name='Montant restant')),
                ('statut', models.CharField(blank=True, max_length=250)),
                ('AnneeScolaire', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='everyfrais_annee', to='Ecole.AnneeScolaire')),
                ('classe', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='classe_eleve', to='Ecole.Classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='eleve_payant', to='Inscriptions.Eleve')),
                ('typeFrais', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='typeFrais', to='Finances.ConfigurationFraisEleve', verbose_name='Type de frais à payer')),
            ],
            options={
                'verbose_name_plural': 'Paiement_Every_Frais',
                'db_table': 'Paiement_Every_Frais',
            },
        ),
        migrations.CreateModel(
            name='ConfigEcolage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(default='Frais mensuels', max_length=100, verbose_name='Intitulé du frais')),
                ('periodePaiement', models.CharField(max_length=100, verbose_name='Période de paiement')),
                ('obligatoire', models.BooleanField(default=True, verbose_name='Frais Obligatoire ?')),
                ('montant', models.FloatField()),
                ('classe', models.CharField(max_length=100)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé_le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié_le')),
                ('AnneeScolaire', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ecolage_annnee', to='Ecole.AnneeScolaire')),
            ],
            options={
                'db_table': 'Config_Ecolage',
            },
        ),
        migrations.CreateModel(
            name='ConfigDepenses',
            fields=[
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé_le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié_le')),
                ('identifiant', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Intitulé du frais')),
                ('periodePaiement', models.CharField(max_length=100, verbose_name='Période de paiement')),
                ('obligatoire', models.BooleanField(default=True, verbose_name='Frais Obligatoire ?')),
                ('montant', models.FloatField(null=True)),
                ('caisseDeRetrait', models.CharField(max_length=100, null=True, verbose_name='Caisse de retrait')),
                ('AnneeScolaire', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='config_depense_annnee', to='Ecole.AnneeScolaire')),
            ],
            options={
                'db_table': 'Config_Depenses',
            },
        ),
        migrations.CreateModel(
            name='ConfigAutresFrais',
            fields=[
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé_le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié_le')),
                ('identifiant', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('periodePaiement', models.CharField(max_length=100, verbose_name='Période de paiement')),
                ('obligatoire', models.BooleanField(default=True, verbose_name='Frais Obligatoire ?')),
                ('montant', models.FloatField()),
                ('AnneeScolaire', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='autresFrais_annnee', to='Ecole.AnneeScolaire')),
                ('classesSpeciales', models.ManyToManyField(related_name='autreFrais_classe', to='Ecole.Classe')),
            ],
            options={
                'verbose_name_plural': 'Configuration_Autres_Frais',
                'db_table': 'Configuration_Autres_Frais',
            },
        ),
    ]
