# Generated by Django 3.0.7 on 2021-09-08 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole', '0005_auto_20210828_0607'),
        ('Finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationfraiseleve',
            name='classe',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ecolage_classe', to='Ecole.Classe'),
        ),
    ]
