# Generated by Django 3.0.7 on 2021-04-07 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole', '0001_initial'),
        ('Finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementfrais',
            name='classe',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='classe_eleve', to='Ecole.Classe'),
        ),
    ]
