# Generated by Django 3.0.7 on 2021-06-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiementfrais',
            name='montantFrais',
            field=models.CharField(max_length=50, verbose_name='Montant Frais à payer'),
        ),
    ]
