# Generated by Django 3.0.7 on 2021-06-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finances', '0002_auto_20210623_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiementfrais',
            name='montantRestant',
            field=models.FloatField(editable=False, verbose_name='Montant restant'),
        ),
    ]
