# Generated by Django 3.0.7 on 2021-07-31 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole', '0001_initial'),
        ('Finances', '0002_configfraisinscriptionreinscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configfraisinscriptionreinscription',
            name='classe',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='inscr_reinsc_classe', to='Ecole.Classe', unique=True),
        ),
    ]
