# Generated by Django 3.0.7 on 2021-08-03 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole', '0001_initial'),
        ('Inscriptions', '0003_auto_20210531_0712'),
        ('Finances', '0003_auto_20210731_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configfraisinscriptionreinscription',
            name='classe',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='inscr_reinsc_classe', to='Ecole.Classe'),
        ),
        migrations.CreateModel(
            name='PaiementInscriptionReinscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé_le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié_le')),
                ('typeFrais', models.CharField(choices=[('Frais Inscription', 'Frais Inscription'), ('Frais Reinscription', 'Frais Reinscription')], max_length=50, null=True, verbose_name='Type de frais à payer')),
                ('montantFrais', models.CharField(max_length=50, verbose_name='Montant Frais à payer')),
                ('classe', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='classe_eleve_insc_reinsc', to='Ecole.Classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='eleve_payant_insc_reinsc', to='Inscriptions.Eleve')),
            ],
            options={
                'db_table': 'Paiement_Inscription_Reinscription',
                'ordering': ['-cree_le'],
            },
        ),
    ]
