# Generated by Django 3.0.7 on 2021-08-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finances', '0004_auto_20210803_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiementinscriptionreinscription',
            name='montantFrais',
            field=models.FloatField(verbose_name='Montant Frais à payer'),
        ),
    ]
