# Generated by Django 3.0.7 on 2021-09-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finances', '0005_auto_20210908_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='configfraisinscriptionreinscription',
            name='periodePaiement',
            field=models.CharField(default='', max_length=100, verbose_name='Période de paiement'),
        ),
    ]
