# Generated by Django 3.0.7 on 2021-07-20 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finances', '0005_auto_20210720_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paiementfrais',
            old_name='moisSolves',
            new_name='moisAsolver',
        ),
    ]
