# Generated by Django 3.0.7 on 2021-09-11 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finances', '0007_auto_20210911_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configautresfrais',
            options={'verbose_name_plural': 'Configuration_Autres_Frais'},
        ),
        migrations.RenameField(
            model_name='configautresfrais',
            old_name='classe',
            new_name='classesSpeciales',
        ),
    ]
