# Generated by Django 3.0.7 on 2021-09-12 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole', '0005_auto_20210828_0607'),
        ('Finances', '0008_auto_20210911_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigDepenses',
            fields=[
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé_le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié_le')),
                ('identifiant', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Intitulé du frais')),
                ('periodePaiement', models.CharField(max_length=100, verbose_name='Période de paiement')),
                ('obligatoire', models.BooleanField(default=True, verbose_name='Frais Obligatoire ?')),
                ('montant', models.FloatField(null=True)),
                ('caisseDeRetrait', models.CharField(max_length=100, null=True, verbose_name='Caisse de retrait')),
                ('AnneeScolaire', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='config_depense_annnee', to='Ecole.AnneeScolaire')),
            ],
            options={
                'db_table': 'Config_Depenses',
            },
        ),
    ]
