# Generated by Django 3.0.7 on 2021-09-14 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole', '0005_auto_20210828_0607'),
        ('Inscriptions', '0001_initial'),
        ('Finances', '0010_auto_20210912_0510'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementEveryFrais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé_le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié_le')),
                ('montantFrais', models.CharField(max_length=50, verbose_name='Montant Frais à payer')),
                ('mois', models.CharField(blank=True, max_length=30, null=True, verbose_name='Mois à payer')),
                ('montantApayer', models.FloatField(verbose_name='Montant à payer')),
                ('montantDejaPaye', models.FloatField(default=0, verbose_name='Montant déjà payé')),
                ('montantRestant', models.FloatField(verbose_name='Montant restant')),
                ('statut', models.CharField(blank=True, max_length=250)),
                ('classe', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='classe_eleve', to='Ecole.Classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='eleve_payant', to='Inscriptions.Eleve')),
                ('typeFrais', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='typeFrais', to='Finances.ConfigurationFraisEleve', verbose_name='Type de frais à payer')),
            ],
            options={
                'verbose_name_plural': 'Paiement_Every_Frais',
                'db_table': 'Paiement_Every_Frais',
            },
        ),
    ]
