# Generated by Django 3.0.7 on 2021-09-14 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole', '0005_auto_20210828_0607'),
        ('Finances', '0011_paiementeveryfrais'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementeveryfrais',
            name='AnneeScolaire',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='everyfrais_annee', to='Ecole.AnneeScolaire'),
        ),
    ]
