# Generated by Django 3.0.7 on 2021-09-14 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finances', '0012_paiementeveryfrais_anneescolaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiementinscriptionreinscription',
            name='typeFrais',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='InscReinsc_type_frais', to='Finances.ConfigurationFraisEleve', verbose_name='Type de frais à payer'),
        ),
    ]
