# Generated by Django 3.0.7 on 2021-09-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finances', '0013_auto_20210914_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='configecolage',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configecolage',
            name='identifiant',
            field=models.CharField(default='Frais mensuels', max_length=100, verbose_name='Intitulé du frais'),
        ),
    ]
