# Generated by Django 3.0.7 on 2021-10-20 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finances', '0015_paiementeveryfrais_moisasolver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configecolage',
            name='identifiant',
        ),
    ]
