# Generated by Django 3.0.7 on 2021-10-20 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finances', '0016_remove_configecolage_identifiant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfigEcolage',
        ),
    ]
