# Generated by Django 3.0.7 on 2021-03-27 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ecole', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('identifiant', models.CharField(help_text='taper la salle Ex: 3e', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('heuresCours', models.CharField(default='7h30-13h', max_length=100)),
                ('nbreEleves', models.IntegerField()),
                ('nbreSalles', models.IntegerField(default=1)),
                ('contenance', models.IntegerField()),
                ('totalFilles', models.IntegerField()),
                ('totalGarcons', models.IntegerField()),
                ('matieresEnseigne', models.TextField(max_length=800)),
                ('redoublants', models.IntegerField(default=0)),
                ('nouveaux', models.IntegerField(default=0)),
                ('elevesVenuDailleurs', models.IntegerField(default=0)),
                ('inscrits', models.IntegerField()),
                ('scolarite', models.CharField(choices=[('5.000f', '5.000 FCFA'), ('7000f', '7000 FCFA'), ('8000f', '8000 FCFA'), ('9000f', '9000 FCFA'), ('10000f', '10000 FCFA'), ('12000f', '12000 FCFA')], default='', max_length=50)),
                ('referenceSite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
