# Generated by Django 3.0.7 on 2021-03-22 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ecole', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(default='Crèche', max_length=50)),
                ('nbreEleves', models.IntegerField()),
                ('nbreSalles', models.IntegerField(default=1)),
                ('contenance', models.IntegerField()),
                ('totalFilles', models.IntegerField()),
                ('totalGarcons', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Crèche',
            },
        ),
        migrations.CreateModel(
            name='CP2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heuresCours', models.CharField(default='7h30-13h', max_length=100)),
                ('nbreEleves', models.IntegerField()),
                ('nbreSalles', models.IntegerField(default=1)),
                ('contenance', models.IntegerField()),
                ('totalFilles', models.IntegerField()),
                ('totalGarcons', models.IntegerField()),
                ('matieresEnseigne', models.TextField(max_length=800)),
                ('redoublants', models.IntegerField(default=0)),
                ('nouveaux', models.IntegerField(default=0)),
                ('elevesVenuDailleurs', models.IntegerField(default=0)),
                ('inscrits', models.IntegerField()),
                ('identifiant', models.CharField(default='CP2', max_length=50)),
                ('referenceSite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CP1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heuresCours', models.CharField(default='7h30-13h', max_length=100)),
                ('nbreEleves', models.IntegerField()),
                ('nbreSalles', models.IntegerField(default=1)),
                ('contenance', models.IntegerField()),
                ('totalFilles', models.IntegerField()),
                ('totalGarcons', models.IntegerField()),
                ('matieresEnseigne', models.TextField(max_length=800)),
                ('redoublants', models.IntegerField(default=0)),
                ('nouveaux', models.IntegerField(default=0)),
                ('elevesVenuDailleurs', models.IntegerField(default=0)),
                ('inscrits', models.IntegerField()),
                ('identifiant', models.CharField(default='CP1', max_length=50)),
                ('referenceSite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heuresCours', models.CharField(default='7h30-13h', max_length=100)),
                ('nbreEleves', models.IntegerField()),
                ('nbreSalles', models.IntegerField(default=1)),
                ('contenance', models.IntegerField()),
                ('totalFilles', models.IntegerField()),
                ('totalGarcons', models.IntegerField()),
                ('matieresEnseigne', models.TextField(max_length=800)),
                ('redoublants', models.IntegerField(default=0)),
                ('nouveaux', models.IntegerField(default=0)),
                ('elevesVenuDailleurs', models.IntegerField(default=0)),
                ('inscrits', models.IntegerField()),
                ('referenceSite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
