# Generated by Django 3.0.7 on 2021-03-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='scolarite',
            field=models.CharField(help_text='Frais à payer mensuellement Eg: 8000F', max_length=50),
        ),
    ]
