# Generated by Django 3.0.7 on 2021-08-27 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ecole', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('eleveNumber', models.AutoField(auto_created=True, db_column='n°', primary_key=True, serialize=False, verbose_name='n°:')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé_le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié_le')),
                ('nom', models.CharField(help_text='Tapez tous les noms et prénoms', max_length=255, unique=True)),
                ('sexe', models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin')], default='', max_length=255)),
                ('dateLieuNaissance', models.CharField(help_text='Tapez  la date et le lieu de Naissance Eg: 11-Mai-1995 à Brazzaville', max_length=100)),
                ('adresse', models.CharField(max_length=250, verbose_name="Domicile de l'élève")),
                ('etatSanitaire', models.CharField(choices=[('Apte', 'Apte'), ('Inapte', 'Inapte')], default=('Apte', 'Apte'), max_length=20, verbose_name='Etat sanitaire')),
                ('ecoleDorigine', models.CharField(default='Saint Martin', max_length=255, verbose_name="Ecole d'origine")),
                ('nomMaman', models.CharField(help_text='Tapez tous les noms et prénoms', max_length=255, null=True, verbose_name='Nom de la mère')),
                ('telMaman', models.CharField(blank=True, max_length=15, null=True, verbose_name='Tel de la mère')),
                ('nomPapa', models.CharField(help_text='Tapez tous les noms et prénoms', max_length=255, null=True, verbose_name='Nom du père')),
                ('telPapa', models.CharField(blank=True, max_length=15, null=True, verbose_name='Tel du la père')),
                ('tuteur', models.CharField(max_length=255)),
                ('telTuteur', models.CharField(max_length=15, verbose_name='Tel du tuteur')),
                ('emailTuteur', models.EmailField(blank=True, max_length=255, null=True, verbose_name='email du tuteur')),
                ('dateInscription', models.DateField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('redoublant', models.CharField(choices=[('Nouveau', 'Nouveau'), ('Redoublant', 'Redoublant')], default=('Nouveau', 'Nouveau'), max_length=25)),
                ('AnneeScolaire', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='eleve_annee_scolaire', to='Ecole.AnneeScolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eleve', to='Ecole.Classe')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
