# Generated by Django 3.0.7 on 2021-03-26 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Classe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Tapez tous les noms et prénoms', max_length=255, unique=True)),
                ('sexe', models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin')], default='', max_length=255)),
                ('naissance', models.DateField(auto_now_add=True)),
                ('age', models.CharField(default='26 ans', max_length=20)),
                ('lieuNaiss', models.CharField(db_column='lieuDeNaissance', default='Brazzaville', max_length=50)),
                ('dateInscrit', models.DateField(auto_now_add=True)),
                ('scolarite', models.CharField(default='', editable=False, max_length=50)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classe.Classe')),
            ],
        ),
    ]
