# Generated by Django 3.0.7 on 2021-05-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='lieuNaiss',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='scolarite',
        ),
        migrations.AddField(
            model_name='eleve',
            name='adresse',
            field=models.CharField(default='4,rue Makanga-Annie, Moussosso', max_length=250, verbose_name="Domicile de l'élève"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eleve',
            name='nomMaman',
            field=models.CharField(help_text='Tapez tous les noms et prénoms', max_length=255, null=True, verbose_name='Nom de la mère'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='nomPapa',
            field=models.CharField(help_text='Tapez tous les noms et prénoms', max_length=255, null=True, verbose_name='Nom du père'),
        ),
    ]
