# Generated by Django 3.0.7 on 2021-10-21 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole', '0002_auto_20211021_1137'),
        ('Inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='AnneeScolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='eleve_annee_scolaire', to='Ecole.AnneeScolaire'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='eleve', to='Ecole.Classe'),
        ),
    ]
