# Generated by Django 3.0.7 on 2021-03-28 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='age',
            field=models.CharField(default='2021 - <function Eleve.<lambda> at 0x0000005E77ED7790> ans', editable=False, max_length=50),
        ),
    ]
