# Generated by Django 3.0.7 on 2021-03-26 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Classe', '0001_initial'),
        ('Inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classeEleve', to='Classe.Classe'),
        ),
    ]
