# Generated by Django 3.0.7 on 2021-03-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inscriptions', '0002_eleve_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='age',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
