# Generated by Django 3.0.7 on 2021-05-31 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Inscriptions', '0002_auto_20210529_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='naissance',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='nationalite',
        ),
        migrations.AddField(
            model_name='eleve',
            name='dateLieuNaissance',
            field=models.CharField(default=django.utils.timezone.now, help_text='Tapez  la date et le lieu de Naissance Eg: 11-Mai-1995 à Brazzaville', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eleve',
            name='emailTuteur',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='email du tuteur'),
        ),
    ]
