# Generated by Django 3.0.7 on 2021-04-01 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Classe', '0002_auto_20210328_0626'),
        ('Inscriptions', '0003_auto_20210328_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eleve', to='Classe.Classe'),
        ),
    ]
