# Generated by Django 3.0.7 on 2021-04-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedagogie', '0002_auto_20210410_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='moyenne_generale_matiere',
            field=models.FloatField(editable=False, null=True),
        ),
    ]
