# Generated by Django 3.0.7 on 2021-03-26 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeSite2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbreSalles', models.IntegerField(default=4)),
                ('salles6e', models.IntegerField(default=1)),
                ('salles5e', models.IntegerField(default=1)),
                ('salles4e', models.IntegerField(default=1)),
                ('salles3e', models.IntegerField(default=1)),
                ('contenance6e', models.IntegerField()),
                ('contenance5e', models.IntegerField()),
                ('contenance4e', models.IntegerField()),
                ('contenance3e', models.IntegerField()),
                ('matieres', models.TextField(default='Français, Histoire, Géographie, Anglais, Mathématiques, SVT, Physique-Chimie, EPS, Informatique, Musique')),
            ],
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescolaire', models.CharField(default='Garderie', max_length=250)),
                ('primaire', models.CharField(default='Prescolaire', max_length=250)),
                ('college', models.CharField(default='Primaire', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('nbreSites', models.IntegerField(default=2)),
                ('pays', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('siteInternet', models.CharField(max_length=200, null=True)),
                ('prefixmatricule', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PrimaireSite2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbreSalles', models.IntegerField(default=6)),
                ('sallesCP1', models.IntegerField(default=1)),
                ('sallesCP2', models.IntegerField(default=1)),
                ('sallesCE1', models.IntegerField(default=1)),
                ('sallesCE2', models.IntegerField(default=1)),
                ('sallesCM1', models.IntegerField(default=1)),
                ('sallesCM2', models.IntegerField(default=1)),
                ('contenanceCP1', models.IntegerField()),
                ('contenanceCP2', models.IntegerField()),
                ('contenanceCE1', models.IntegerField(default=1)),
                ('contenanceCE2', models.IntegerField(default=1)),
                ('contenanceCM1', models.IntegerField(default=1)),
                ('contenanceCM2', models.IntegerField(default=1)),
                ('matieres', models.TextField(default='Français, Histoire  --   Mathématiques, SVT, Mesures  --   Education_culturelle, ...')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=1)),
                ('adresseSite', models.CharField(max_length=250)),
                ('cycles', models.CharField(max_length=250)),
                ('nombreCycles', models.IntegerField(default=2)),
                ('nbreSalleGarderie', models.IntegerField(default=0)),
                ('nbreSallePrimaire', models.IntegerField(default=6)),
                ('nbreSalleCollege', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='PrimaireSite1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbreSalles', models.IntegerField(default=11)),
                ('sallesCP1', models.IntegerField(default=2)),
                ('sallesCP2', models.IntegerField(default=2)),
                ('sallesCE1', models.IntegerField(default=2)),
                ('sallesCE2', models.IntegerField(default=2)),
                ('sallesCM1', models.IntegerField(default=2)),
                ('sallesCM2', models.IntegerField(default=1)),
                ('contenanceCP1', models.IntegerField()),
                ('contenanceCP2', models.IntegerField()),
                ('contenanceCE1', models.IntegerField()),
                ('contenanceCE2', models.IntegerField()),
                ('contenanceCM1', models.IntegerField()),
                ('contenanceCM2', models.IntegerField()),
                ('matieres', models.TextField(default='Français, Histoire, Mathématiques, SVT, Mesures, Education_culturelle, ...')),
                ('numeroSite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole.Site')),
            ],
        ),
        migrations.CreateModel(
            name='GarderieSite1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbreSalles', models.IntegerField(default=2)),
                ('contenance', models.IntegerField()),
                ('numeroSite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole.Site')),
            ],
        ),
        migrations.CreateModel(
            name='CollegeSite1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbreSalles', models.IntegerField(default=8)),
                ('salles6e', models.IntegerField(default=2)),
                ('salles5e', models.IntegerField(default=2)),
                ('salles4e', models.IntegerField(default=2)),
                ('salles3e', models.IntegerField(default=2)),
                ('contenance6e', models.IntegerField()),
                ('contenance5e', models.IntegerField()),
                ('contenance4e', models.IntegerField()),
                ('contenance3e', models.IntegerField()),
                ('matieres', models.TextField(default='Français, Histoire, Géographie, Anglais, Mathématiques, SVT, Physique-Chimie, EPS, Informatique, Musique')),
                ('numeroSite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole.Site')),
            ],
        ),
    ]
