# Generated by Django 3.0.7 on 2021-05-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='matiereDeBase',
            field=models.CharField(choices=[('Non', 'Non'), ('Oui', 'Oui')], max_length=50, null=True, verbose_name='Matiere de Base ?'),
        ),
    ]
