# Generated by Django 3.0.7 on 2021-08-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='identifiant',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
