# Generated by Django 3.0.7 on 2021-10-21 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anneescolaire',
            name='anneeScolaire',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Annee scolaire actuelle'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='anneeScolaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='classe_annee_scolaire', to='Ecole.AnneeScolaire', verbose_name='Année Scolaire'),
        ),
        migrations.RemoveField(
            model_name='classe',
            name='cycle',
        ),
        migrations.AddField(
            model_name='classe',
            name='cycle',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='classeCycle', to='Ecole.Cycle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classe',
            name='identifiant',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='classe',
            name='scolarite',
            field=models.CharField(help_text='Frais à payer mensuellement Eg: 8000F', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='nomCycle',
            field=models.CharField(choices=[('Garderie', 'Garderie'), ('Prescolaire', 'Prescolaire'), ('Primaire', 'Primaire'), ('College', 'College'), ('Lycée', 'Lycée')], default=('Garderie', 'Garderie'), max_length=50, primary_key=True, serialize=False, verbose_name='Nom du cycle'),
        ),
    ]
