# Generated by Django 3.0.7 on 2021-05-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='pluriProf',
            field=models.CharField(choices=[('Non', 'Non'), ('Oui', 'Oui')], default=('Non', 'Non'), max_length=20, verbose_name='Enseignée par plusieurs ?'),
        ),
    ]
