# Generated by Django 3.0.7 on 2021-03-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garderiesite1',
            name='contenance',
            field=models.IntegerField(),
        ),
    ]
