# Generated by Django 3.0.7 on 2021-04-10 03:21

import ApiRest.Ecole.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='annee_academique',
            field=models.CharField(default=ApiRest.Ecole.models.Classe.anneeAcademique, editable=False, max_length=50, verbose_name='Année académique :'),
        ),
    ]
