# Generated by Django 3.0.7 on 2021-05-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole', '0002_auto_20210512_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='nomMatiere',
            field=models.CharField(default='', max_length=200, unique=True, verbose_name='nom de la matière'),
        ),
    ]
