# Generated by Django 3.0.7 on 2021-03-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole', '0002_auto_20210320_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='numero',
            field=models.IntegerField(default=1),
        ),
    ]
