# Generated by Django 3.0.7 on 2021-05-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole', '0003_auto_20210512_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='codeMatiere',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Code de la matière'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='groupeMatiere',
            field=models.CharField(choices=[('MATIERE_LITTERAIRES', 'Matières litteraires'), ('MATIERE_SCIENTIFIQUES', 'Matières scientifiques'), ('AUTRES_MATIERES', 'Autres matières')], max_length=100, null=True),
        ),
    ]
