# Generated by Django 3.0.7 on 2021-08-27 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole', '0003_auto_20210827_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='cycle',
        ),
        migrations.AddField(
            model_name='classe',
            name='cycle',
            field=models.ForeignKey(default='Prescolaire', on_delete=django.db.models.deletion.DO_NOTHING, related_name='classe_cycle', to='Ecole.Cycle'),
            preserve_default=False,
        ),
    ]
