# Generated by Django 3.0.7 on 2021-05-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole', '0004_auto_20210512_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='groupeMatiere',
            field=models.CharField(choices=[('MATIERE_LITTERAIRES', 'Matières litteraires'), ('MATIERE_SCIENTIFIQUES', 'Matières scientifiques'), ('AUTRES_MATIERES', 'Autres matières')], max_length=100, null=True, verbose_name='Groupe Matière'),
        ),
    ]
