# Generated by Django 3.0.7 on 2021-08-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole', '0004_auto_20210827_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='nomCycle',
            field=models.CharField(choices=[('Garderie', 'Garderie'), ('Prescolaire', 'Prescolaire'), ('Primaire', 'Primaire'), ('College', 'College'), ('Lycée', 'Lycée')], default=('Garderie', 'Garderie'), max_length=50, primary_key=True, serialize=False, verbose_name='Nom du cycle'),
        ),
    ]
