# Generated by Django 3.0.7 on 2021-05-14 15:45

import ApiRest.Ecole.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole', '0005_auto_20210512_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enseignant',
            options={'ordering': ['-creeLe']},
        ),
        migrations.RenameField(
            model_name='enseignant',
            old_name='cree_le',
            new_name='creeLe',
        ),
        migrations.RenameField(
            model_name='enseignant',
            old_name='intitule_du_compte',
            new_name='intituleCompte',
        ),
        migrations.RenameField(
            model_name='enseignant',
            old_name='mode_paiement',
            new_name='modePaiement',
        ),
        migrations.RenameField(
            model_name='enseignant',
            old_name='modifie_at',
            new_name='modifieLe',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='annee_academique',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='category',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='classes_occupees',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='date_d_embauche',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='matiere_enseigne',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='numero_cnss',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='numero_du_compte_bancaire',
        ),
        migrations.AddField(
            model_name='classe',
            name='anneeAcademique',
            field=models.CharField(default=ApiRest.Ecole.models.Classe.anneeAcademique, editable=False, max_length=50, verbose_name='Année académique :'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='classesOccupees',
            field=models.ManyToManyField(related_name='enseignant_classes', to='Ecole.Classe', verbose_name='Classe(s) à enseigner'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='dateEmbauche',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Date d'embauche"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enseignant',
            name='enseigneAu',
            field=models.CharField(choices=[('Primaire', 'Primaire'), ('College', 'College'), ('Maternelle', 'Maternelle')], default=('College', 'College'), max_length=30, verbose_name='Enseigne au cycle :'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='matiereEnseigne',
            field=models.ManyToManyField(default='', related_name='enseignant_matieres', to='Ecole.Matiere', verbose_name='Matière(s) enseignée(s)'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='numeroCnss',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Numéro CNSS'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='numeroCompteBancaire',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Numéro compte bancaire'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='groupeMatiere',
            field=models.CharField(blank=True, choices=[('MATIERE_LITTERAIRES', 'Matières litteraires'), ('MATIERE_SCIENTIFIQUES', 'Matières scientifiques'), ('AUTRES_MATIERES', 'Autres matières')], default='', max_length=100, verbose_name='Groupe Matière'),
        ),
    ]
