# Generated by Django 3.0.7 on 2021-10-20 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole', '0005_auto_20210828_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='classeCycle', to='Ecole.Cycle'),
        ),
    ]
