# Generated by Django 3.0.7 on 2021-05-14 15:48

import ApiRest.Ecole.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole', '0006_auto_20210514_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='situation_sociale',
        ),
        migrations.AddField(
            model_name='enseignant',
            name='situationSociale',
            field=models.CharField(choices=[('Marie', 'Marié(e)'), ('Divorce', 'Divorcé(e)'), ('Fiance', 'Fiancé(e)'), ('Veuf', 'Veuf(ve)'), ('Celibataire', 'Célibataire')], default=django.utils.timezone.now, max_length=50, verbose_name='Situation sociale'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classe',
            name='anneeAcademique',
            field=models.CharField(default=ApiRest.Ecole.models.Classe.anneeAcademique, editable=False, max_length=50, verbose_name='Année académique :'),
        ),
    ]
