# Generated by Django 3.0.7 on 2021-10-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole', '0006_auto_20211020_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anneescolaire',
            name='anneeScolaire',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Annee scolaire actuelle'),
        ),
    ]
