# Generated by Django 3.0.7 on 2021-05-27 04:41

import ApiRest.Ecole.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole', '0008_auto_20210526_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='anneeAcademique',
            field=models.CharField(default=ApiRest.Ecole.models.Classe.anneeAcademique, editable=False, max_length=50, verbose_name='Année académique :'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='dateEmbauche',
            field=models.DateField(auto_now_add=True, verbose_name='créé_le'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='intituleCompte',
            field=models.CharField(blank=True, default=None, help_text="Ecrire le nom du compte bancaire de l'enseignant", max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='numeroCnss',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True, verbose_name='Numéro CNSS'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='numeroCompteBancaire',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, unique=True, verbose_name='Numéro compte bancaire'),
        ),
    ]
