# Generated by Django 3.0.7 on 2021-08-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationSalairePersonnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé_le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié_le')),
                ('categoriePersonnel', models.CharField(choices=[('Surveillant', 'Surveillant'), ('Caissier', 'Caissier'), ('Directeurs', (('PDG', 'Promoteur'), ('DG', 'Directeur Général'), ('DE', 'Directeur des Etudes'))), ('Agent De propreté', 'Agent de propreté'), ('Agent de sécurité', 'Agent de sécurité')], max_length=50, verbose_name="Catégorie d'employé :")),
                ('salaireDefini', models.FloatField(verbose_name='Salaire défini')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('personnelNumero', models.AutoField(auto_created=True, db_column='n°', primary_key=True, serialize=False, verbose_name='N°:')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé_le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié_le')),
                ('nom', models.CharField(help_text='Tapez tous les noms et prénoms', max_length=255, unique=True)),
                ('civilite', models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin')], default='', max_length=255)),
                ('dateNaissance', models.CharField(help_text='Tappez juste la date de Naissance Eg: 11-Mai-1995', max_length=50, verbose_name='Date de Naissance')),
                ('lieuNaissance', models.CharField(blank=True, db_column='lieuDeNaissance', default='Brazzaville', max_length=50, verbose_name='Lieu de Naissance')),
                ('statutMatrimonial', models.CharField(choices=[('Marié(e)', 'Marié(e)'), ('Divorcé(e)', 'Divorcé(e)'), ('Fiancé(e)', 'Fiancé(e)'), ('Veuf(ve)', 'Veuf(ve)'), ('Célibataire', 'Célibataire')], max_length=50, verbose_name='Statut matrimonial')),
                ('nationalite', models.CharField(default='Congolaise', max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('dateEmbauche', models.DateField(verbose_name="Date d'embauche")),
                ('posteOccupe', models.CharField(choices=[('Surveillant', 'Surveillant'), ('Caissier', 'Caissier'), ('Directeurs', (('PDG', 'Promoteur'), ('DG', 'Directeur Général'), ('DE', 'Directeur des Etudes'))), ('Agent De propreté', 'Agent de propreté'), ('Agent de sécurité', 'Agent de sécurité')], max_length=50, verbose_name='Embauché en qualité de :')),
                ('modePaiement', models.CharField(choices=[('Manuel', 'Manuel'), ('Virement', 'Virement Bancaire')], default=('Manuel', 'Manuel'), max_length=100, verbose_name='Mode de paiement')),
                ('intituleCompte', models.CharField(blank=True, help_text="Ecrire le nom du compte bancaire de l'enseignant", max_length=250, null=True, unique=True, verbose_name='Intitulé du compte banquaire')),
                ('numeroCompteBancaire', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Numero du compte bancaire')),
                ('numeroCnss', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Numero Cnss')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
    ]
