# Generated by Django 3.0.7 on 2021-04-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRH', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationSalairePersonnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé_le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié_le')),
                ('categorie_personnel', models.CharField(choices=[('Surveillant', 'Surveillant'), ('Caissier', 'Caissier'), ('Directeurs', (('PDG', 'Promoteur'), ('DG', 'Directeur Général'), ('DE', 'Directeur des Etudes'))), ('Agent De propreté', 'Agent de propreté'), ('Agent de sécurité', 'Agent de sécurité')], max_length=50, verbose_name="Catégorie d'employé :")),
                ('salaire_defini', models.FloatField(verbose_name='Salaire défini')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ConfigSalairePersonnel',
        ),
    ]
