# Generated by Django 3.0.7 on 2021-05-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRH', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='statutMatrimonial',
            field=models.CharField(choices=[('Marié(e)', 'Marié(e)'), ('Divorcé(e)', 'Divorcé(e)'), ('Fiancé(e)', 'Fiancé(e)'), ('Veuf(ve)', 'Veuf(ve)'), ('Célibataire', 'Célibataire')], max_length=50, verbose_name='Statut matrimonial'),
        ),
    ]
